# -*- coding: utf-8 -*-
"""Languages the site is published in, and every string of chrome around the
stories. Hebrew is the original and lives at the site root; each translation
gets its own directory so every language is a separate indexable URL."""

SITE = "https://shayh22.github.io/tells"

LANGS = ["he", "en", "ru", "es", "zh"]

META = {
    "he": {"dir": "rtl", "path": "",     "locale": "he_IL", "native": "עברית",   "label": "עברית"},
    "en": {"dir": "ltr", "path": "en/",  "locale": "en_US", "native": "English", "label": "English"},
    "ru": {"dir": "ltr", "path": "ru/",  "locale": "ru_RU", "native": "Русский", "label": "Русский"},
    "es": {"dir": "ltr", "path": "es/",  "locale": "es_ES", "native": "Español", "label": "Español"},
    "zh": {"dir": "ltr", "path": "zh/",  "locale": "zh_CN", "native": "中文",     "label": "中文"},
}

UI = {
    "he": {
        "site": "אגדות המראה",
        "tagline": "אסופת משלים מודרניים על מנגנוני הגנה רגשיים, דפוסי תקשורת בזוגיות, והדרך לריפוי פנימי",
        "site_title": "אגדות המראה: אסופת סיפורים על לב, פחד ואהבה",
        "footer": "אגדות המראה • משלים מודרניים על לב, פחד ואהבה",
        "toc": "תוכן העניינים",
        "all_stories": "כל הסיפורים",
        "story_of": "סיפור %d מתוך %d",
        "prev": "הסיפור הקודם",
        "next": "הסיפור הבא",
        "moral": "מוסר השכל",
        "illustrations": "%d איורים",
        "hero_caption": "מה שהמראה מחזירה תלוי במי שמביט בה.",
        "topic": "נושא: %s",
        "share": "שיתוף העמוד",
        "share_done": "הקישור הועתק",
        "contact": "צור קשר במייל",
        "bigger": "הגדלת גודל הטקסט",
        "smaller": "הקטנת גודל הטקסט",
        "theme": "מצב בהיר / כהה",
        "theme_aria": "מעבר בין מצב בהיר לכהה",
        "lang": "שפה",
        "lang_aria": "בחירת שפה",
        "a11y": "תפריט נגישות",
        "a11y_close": "סגירת תפריט הנגישות",
        "a11y_size": "גודל טקסט",
        "a11y_contrast": "ניגודיות גבוהה",
        "a11y_gray": "גווני אפור",
        "a11y_underline": "הדגשת קישורים",
        "a11y_font": "גופן קריא",
        "a11y_motion": "עצירת אנימציות",
        "a11y_reset": "איפוס הגדרות הנגישות",
        "credit_lead": "פותח על ידי",
        "credit_name": "ברכת הנשיא",
        "credit_tag": "פיתוח תוכנה מותאם, במהירות הבזק, בטכנולוגיית AI",
        "credit_aria": "פותח על ידי ברכת הנשיא — אתר רשמי",
        "engage": "לייקים ותגובות",
        "nav_aria": "ניווט בין סיפורים",
    },
    "en": {
        "site": "Tales of the Mirror",
        "tagline": "Modern fables about emotional defences, the patterns couples fall into, and the road back to yourself",
        "site_title": "Tales of the Mirror: stories of the heart, of fear and of love",
        "footer": "Tales of the Mirror • modern fables of the heart, of fear and of love",
        "toc": "Contents",
        "all_stories": "All stories",
        "story_of": "Story %d of %d",
        "prev": "Previous story",
        "next": "Next story",
        "moral": "The moral",
        "illustrations": "%d illustrations",
        "hero_caption": "What the mirror gives back depends on who is looking into it.",
        "topic": "Theme: %s",
        "share": "Share this page",
        "share_done": "Link copied",
        "contact": "Get in touch by email",
        "bigger": "Increase text size",
        "smaller": "Decrease text size",
        "theme": "Light / dark mode",
        "theme_aria": "Switch between light and dark mode",
        "lang": "Language",
        "lang_aria": "Choose a language",
        "a11y": "Accessibility menu",
        "a11y_close": "Close the accessibility menu",
        "a11y_size": "Text size",
        "a11y_contrast": "High contrast",
        "a11y_gray": "Greyscale",
        "a11y_underline": "Underline links",
        "a11y_font": "Plain reading font",
        "a11y_motion": "Stop animations",
        "a11y_reset": "Reset accessibility settings",
        "credit_lead": "Built by",
        "credit_name": "Birkat HaNasi",
        "credit_tag": "Custom software development, at lightning speed, powered by AI",
        "credit_aria": "Built by Birkat HaNasi — official site",
        "engage": "Likes and comments",
        "nav_aria": "Story navigation",
    },
    "ru": {
        "site": "Сказания зеркала",
        "tagline": "Современные притчи о душевной защите, о том, во что складываются отношения, и о пути к себе",
        "site_title": "Сказания зеркала: истории о сердце, страхе и любви",
        "footer": "Сказания зеркала • современные притчи о сердце, страхе и любви",
        "toc": "Содержание",
        "all_stories": "Все истории",
        "story_of": "История %d из %d",
        "prev": "Предыдущая история",
        "next": "Следующая история",
        "moral": "Мораль",
        "illustrations": "%d иллюстраций",
        "hero_caption": "Что вернёт зеркало — зависит от того, кто в него смотрит.",
        "topic": "Тема: %s",
        "share": "Поделиться страницей",
        "share_done": "Ссылка скопирована",
        "contact": "Связаться по почте",
        "bigger": "Увеличить размер текста",
        "smaller": "Уменьшить размер текста",
        "theme": "Светлый / тёмный режим",
        "theme_aria": "Переключить светлый и тёмный режим",
        "lang": "Язык",
        "lang_aria": "Выбор языка",
        "a11y": "Меню доступности",
        "a11y_close": "Закрыть меню доступности",
        "a11y_size": "Размер текста",
        "a11y_contrast": "Высокая контрастность",
        "a11y_gray": "Оттенки серого",
        "a11y_underline": "Подчёркивать ссылки",
        "a11y_font": "Простой шрифт для чтения",
        "a11y_motion": "Остановить анимацию",
        "a11y_reset": "Сбросить настройки доступности",
        "credit_lead": "Разработано",
        "credit_name": "Birkat HaNasi",
        "credit_tag": "Разработка ПО на заказ — молниеносно, на технологии ИИ",
        "credit_aria": "Разработано Birkat HaNasi — официальный сайт",
        "engage": "Лайки и комментарии",
        "nav_aria": "Навигация по историям",
    },
    "es": {
        "site": "Cuentos del espejo",
        "tagline": "Fábulas modernas sobre las defensas del alma, los patrones en que caen las parejas y el camino de vuelta a uno mismo",
        "site_title": "Cuentos del espejo: relatos del corazón, del miedo y del amor",
        "footer": "Cuentos del espejo • fábulas modernas del corazón, del miedo y del amor",
        "toc": "Índice",
        "all_stories": "Todos los cuentos",
        "story_of": "Cuento %d de %d",
        "prev": "Cuento anterior",
        "next": "Cuento siguiente",
        "moral": "La moraleja",
        "illustrations": "%d ilustraciones",
        "hero_caption": "Lo que el espejo devuelve depende de quién se mire en él.",
        "topic": "Tema: %s",
        "share": "Compartir esta página",
        "share_done": "Enlace copiado",
        "contact": "Escríbeme por correo",
        "bigger": "Aumentar el tamaño del texto",
        "smaller": "Reducir el tamaño del texto",
        "theme": "Modo claro / oscuro",
        "theme_aria": "Cambiar entre modo claro y oscuro",
        "lang": "Idioma",
        "lang_aria": "Elegir idioma",
        "a11y": "Menú de accesibilidad",
        "a11y_close": "Cerrar el menú de accesibilidad",
        "a11y_size": "Tamaño del texto",
        "a11y_contrast": "Alto contraste",
        "a11y_gray": "Escala de grises",
        "a11y_underline": "Subrayar enlaces",
        "a11y_font": "Tipografía de lectura sencilla",
        "a11y_motion": "Detener animaciones",
        "a11y_reset": "Restablecer accesibilidad",
        "credit_lead": "Desarrollado por",
        "credit_name": "Birkat HaNasi",
        "credit_tag": "Desarrollo de software a medida, a la velocidad del rayo, con tecnología de IA",
        "credit_aria": "Desarrollado por Birkat HaNasi — sitio oficial",
        "engage": "Me gusta y comentarios",
        "nav_aria": "Navegación entre cuentos",
    },
    "zh": {
        "site": "明镜寓言",
        "tagline": "关于心防、亲密关系中的固有模式，以及回到自己身上的现代寓言",
        "site_title": "明镜寓言：关于心、恐惧与爱的故事",
        "footer": "明镜寓言 • 关于心、恐惧与爱的现代寓言",
        "toc": "目录",
        "all_stories": "全部故事",
        "story_of": "第 %d 篇，共 %d 篇",
        "prev": "上一篇",
        "next": "下一篇",
        "moral": "寓意",
        "illustrations": "%d 幅插画",
        "hero_caption": "镜子映出什么，取决于凝视它的人。",
        "topic": "主题：%s",
        "share": "分享此页",
        "share_done": "链接已复制",
        "contact": "通过邮件联系",
        "bigger": "放大文字",
        "smaller": "缩小文字",
        "theme": "浅色 / 深色模式",
        "theme_aria": "切换浅色与深色模式",
        "lang": "语言",
        "lang_aria": "选择语言",
        "a11y": "无障碍选单",
        "a11y_close": "关闭无障碍选单",
        "a11y_size": "文字大小",
        "a11y_contrast": "高对比度",
        "a11y_gray": "灰阶",
        "a11y_underline": "为链接加下划线",
        "a11y_font": "易读字体",
        "a11y_motion": "停止动画",
        "a11y_reset": "重置无障碍设置",
        "credit_lead": "开发者",
        "credit_name": "Birkat HaNasi",
        "credit_tag": "以 AI 技术，闪电般快速地打造定制软件",
        "credit_aria": "由 Birkat HaNasi 开发 — 官方网站",
        "engage": "点赞与评论",
        "nav_aria": "故事导航",
    },
}
