# -*- coding: utf-8 -*-
"""Spanish translation, stories 1-3. `texts` follows the order of the p/h/moral
blocks in the Hebrew source; `figs` follows the order of its illustrations."""

ES_1_3 = {
1: {
 "title": "La armadura de espejos de Lirión",
 "topic": "hipersensibilidad, baja autoestima y la sensación de ser perseguido",
 "texts": [
  "En el reino del Valle Esmeralda, en lo hondo de un bosque de robles antiguos, vivía una criatura pequeña y dulce, de pelaje suave, llamada <strong>Lirión</strong>. Lirión tenía un corazón de cristal delgado: sentía cada soplo de viento con la fuerza de una tormenta, y cada hoja que caía le sonaba como un trueno.",
  "Pero una sombra pesada seguía a Lirión: creía con todo su corazón que era pequeño, defectuoso e indigno de ser amado. Y como eso pensaba de sí mismo, estaba seguro de que todas las demás criaturas del bosque lo veían exactamente igual, y de que todas ellas, sin una sola excepción, conspiraban para herirlo o para burlarse de él.",
  "El escudo que se volvió muralla",
  "Para proteger su frágil corazón, Lirión se fabricó una vestidura como ninguna otra: una armadura hecha de esquirlas de espejo empañado. Creía que la armadura deslumbraría a cualquiera que lo mirase y lo defendería de las flechas de burla del mundo.",
  "Pero los espejos de aquella armadura estaban deformados: cuando la zorra del bosque miraba hacia él y sonreía con afecto, Lirión veía en los espejos una sonrisa de desprecio y de escarnio. Cuando una bandada de pájaros trinaba con entusiasmo en una rama cercana, Lirión oía murmullos malintencionados que tramaban expulsarlo. Cuando el erizo le ofrecía compartir un fruto jugoso, Lirión estaba seguro de que era un intento de envenenarlo, o de demostrarle que era demasiado débil para buscarse el alimento por sí mismo.",
  "Cada vez que alguien se acercaba, Lirión gruñía, clamaba por la injusticia que se cometía contra él y declaraba el boicot: \"¡No volveré a hablar con ninguno de vosotros jamás! Todos sois crueles, todos estáis en mi contra, ¡y solo yo he quedado a sufrir en este mundo!\"",
  "Echó a la zorra, se apartó de los pájaros y le cerró la puerta en la cara al erizo.",
  "Solo en una torre de vidrio",
  "Con el paso del tiempo, las criaturas del bosque —que querían a Lirión y lo deseaban cerca— intentaron una y otra vez dejar flores, cartas de paz y pequeños regalos en su umbral. Pero en cada gesto Lirión veía una ofensa nueva:",
  "\"Mandan flores para recordarme lo lastimoso que soy —murmuraba con amargura para sí—. Solo intentan acallar su mala conciencia\".",
  "Al final, las criaturas del bosque se cansaron. El dolor de que toda intención bondadosa fuera leída como crueldad deliberada se volvió una carga demasiado pesada. Empezaron a guardar distancia, rodeando su casa en silencio para no despertar su ira.",
  "Lirión se sentaba dentro de su casa a oscuras, envuelto en la pesada armadura de espejos, y miraba por la ventana. Cuando vio el bosque vacío a su alrededor, lágrimas ardientes le corrieron por las mejillas:",
  "\"Lo sabía —susurró con un dolor abrasador—. Sabía que todos me odiaban. Mirad cómo me han expulsado y me han dejado solo en el mundo. Todos están contra mí, y yo soy la pobre víctima de todos ellos\".",
  "El viejo búho y el manantial claro",
  "Un día, un búho viejo y sabio, de ojos hondos como la noche, se posó en el alféizar de Lirión. Lirión frunció el ceño al instante y gritó: \"¿También tú has venido a mirarme por encima del hombro y a herirme?\"",
  "El búho no retrocedió ni se ofendió. Solo dijo, en voz baja: \"Querido Lirión, la armadura que llevas es pesadísima. Ven conmigo al manantial de la verdad, en la cima de la montaña. Si el manantial muestra que de verdad todos te odian, me quedaré aquí y te protegeré para siempre\".",
  "Lirión, que quería demostrarle al búho cuánta razón tenía y cuánta culpa tenían todos de su estado, lo siguió.",
  "Cuando llegaron a la cima, Lirión se asomó sobre las aguas más claras del reino. Miró en ellas para ver su figura lastimosa y desterrada, pero solo vio las esquirlas de espejo empañado de su armadura, devolviéndole incontables reflejos de su propio rostro: furioso, asustado y lleno de sufrimiento.",
  "\"Quítate la armadura un momento, Lirión —dijo el búho con dulzura—. Mira el agua sin tus espejos\".",
  "Con manos temblorosas, Lirión aflojó las correas y dejó caer la pesada armadura de espejos. Se inclinó sobre el agua. En lugar de monstruos o enemigos, vio una criatura dulce de ojos hermosos, herida en lo hondo. Y cuando miró a su alrededor sin los espejos deformados, vio de pronto el sendero del bosque tal como era: vio al erizo que, por preocupación, le había dejado junto a la puerta una cesta de fresas frescas; vio a los pájaros que le habían cantado una canción de añoranza; y comprendió que la zorra solo había intentado sonreírle con cariño.",
  "\"Nadie te odiaba, Lirión —susurró el búho—. El único enemigo que te ha cazado alguna vez fue la idea de que no eras digno de amor. Como no creías en tu propio valor, convertiste cada mano tendida en un puño y cada sonrisa en burla. Tú fuiste quien expulsó a un mundo que solo quería abrazarte\".",
  "La curación del corazón",
  "En ese instante algo se rompió dentro de Lirión, no una rotura de dolor, sino una liberación profunda. Dejó la armadura de espejos en la cima de la montaña y bajó al valle con su pelaje desnudo y vulnerable.",
  "Al llegar al valle no exigió protección ni culpó a nadie. Simplemente abrió su puerta, miró a sus vecinos y dijo: \"Me equivoqué. Mi dolor me hacía ver enemigos en vosotros, cuando erais la familia que solo quiso siempre mi bien\".",
  "Y en el bosque Esmeralda nadie le reprochó su pasado. Sencillamente lo acogieron de vuelta, porque durante todo ese tiempo, en cada paso del camino, solo habían estado esperando a que aceptara curarse de su propio miedo.",
  "Cuando una persona vive cautiva de una baja autoestima y de la hipersensibilidad, se convierte a sí misma en el centro de un mundo hostil que no existe. Quien lee cada movimiento como una herida y a cada persona como un enemigo se condena al aislamiento y a la amargura, y se convence de que es la víctima del mundo cuando en verdad es el prisionero de sus propios miedos.",
 ],
 "figs": [
  ("Lirión, una pequeña criatura blanca con un corazón de cristal luminoso, sentado a solas en un bosque antiguo sosteniendo una esquirla de espejo",
   "Lirión y su corazón de cristal delgado: cada soplo de viento le sonaba como una tormenta."),
  ("Lirión con una pesada armadura de esquirlas de espejo empañado, su corazón rojo brillando entre las grietas",
   "La armadura que debía protegerlo: esquirlas de espejo empañado que filtraban todo lo que veía."),
  ("Un erizo ofreciéndole a Lirión un higo maduro, mientras el reflejo en la armadura de espejos muestra al erizo gruñendo y amenazante",
   "El erizo le tendía fruta madura, pero en los espejos deformados parecía un gruñido."),
  ("Lirión con su armadura, sentado encorvado y solo al pie de un árbol, con una cesta de fruta dejada a su lado por las criaturas del bosque que observan de lejos",
   "Los regalos se quedaban donde los dejaban, y el bosque miraba desde lejos: la soledad dentro de una armadura."),
  ("Lirión sin su armadura, radiante bajo una luz cálida, tocando el agua del manantial de la verdad mientras las esquirlas de espejo yacen en la orilla y los animales del bosque lo contemplan",
   "En el manantial de la verdad, sin la armadura, se vio por primera vez, y vio a quienes esperaban en la orilla."),
  ("Lirión de pie al atardecer junto al lago, rodeado por un erizo, un conejo, un tejón, una ardilla y un cervatillo, con las esquirlas de espejo tras él",
   "Al atardecer, dejando atrás las esquirlas, Lirión descubrió que nunca había estado solo."),
 ]},

2: {
 "title": "El lienzo de la verdad de Elrán",
 "topic": "la fijación obsesiva en lo que falta y en los defectos",
 "texts": [
  "En el corazón del reino de la Luz del Alba, donde el sol acariciaba siempre los tejados con luz dorada y los campos daban frutos dulces, vivía el guardián real de los jardines, <strong>Elrán</strong>. Elrán tenía un ojo agudo y una sensibilidad rara para cada pequeño matiz, pero tenía también un rasgo que le oscurecía el mundo entero: nunca lograba ver la luz completa, porque sus ojos se iban siempre, obsesivamente, hacia las manchas oscuras.",
  "Si le tejían una hermosa alfombra de seda con mil hilos de oro y solo tenía una diminuta mancha desvaída, Elrán se plantaba sobre la alfombra, señalaba furioso aquella única mancha y clamaba: \"¡Mirad qué fealdad! Esta alfombra está completamente arruinada, y quien la tejió lo hizo a propósito, ¡para herirme!\"",
  "La especia que faltaba",
  "En su casa, su esposa devota y amorosa había construido con él un mundo entero. Trabajaba, cocinaba, criaba a los hijos y atendía cada una de sus necesidades. Pero Elrán no veía las décadas de entrega, ni las comidas calientes, ni el cuidado sincero. Si ella volvía del mercado habiendo olvidado una especia de veinte, él no veía la cesta llena: veía únicamente la especia que faltaba.",
  "Le echaba en cara que lo despreciaba, que él nunca le había importado y que durante todos aquellos años ella solo había buscado maneras de rebajarlo y de quebrarle el ánimo.",
  "Cuando su familia y sus vecinos lo invitaban a sus celebraciones, Elrán recorría la sala con la mirada como un cazador buscando presa. Si alguien no lo saludaba con una sonrisa lo bastante amplia, si alguien hablaba con otra persona y no se volvía hacia él de inmediato, o si su hermano viajaba a un acto familiar sin avisarle antes, Elrán se llenaba de un ardor interior.",
  "Convertía cada gesto inocente en una trama malintencionada, se apartaba de sus parientes, declaraba que eran \"enemigos que destruyeron su alma\" y exigía que todos a su alrededor los boicotearan también, como prueba de lealtad absoluta a su dolor.",
  "Con los años, Elrán se volvió un hombre solitario, amargado y agotado. Su casa se convirtió en una fortaleza donde cada palabra se pesaba por miedo a desatar una nueva tormenta de acusaciones. Estaba convencido de ser el hombre más agraviado y más herido de todo el reino, de que el mundo entero tejía intrigas contra él y de que nadie comprendía la hondura de su sufrimiento.",
  "El lienzo de la verdad",
  "Un día llegó a la ciudad un viejo tejedor sabio con un lienzo como ningún otro: <strong>el \"Lienzo de la Verdad\"</strong>. El lienzo era blanco, suave y magnífico, y en su centro había un pequeño punto negro de tinta, del tamaño de un grano de sésamo. El tejedor lo montó en la plaza del pueblo e invitó a la gente a mirarlo.",
  "Elrán se plantó ante el lienzo, su mirada se clavó al instante en la mancha negra y su rostro enrojeció de ira: \"¡Qué vergüenza! ¿Cómo os atrevéis a exhibir en la plaza un lienzo tan manchado, tan feo y tan defectuoso? ¡Os estáis burlando de todos nosotros!\"",
  "El viejo tejedor miró a Elrán con ojos serenos y compasivos, y le preguntó con calma: \"Elrán, mira bien. Aquí tienes una sábana enorme de seda blanca purísima, mil hilos de luz, meses de trabajo destinados a traer calor y belleza. ¿Por qué, de toda esta extensión blanca y magnífica, has elegido ver solo el granito de tinta y juzgar por él el lienzo entero?\"",
  "Elrán se quedó helado donde estaba, sin palabras.",
  "\"Buscas el defecto porque por dentro te sientes defectuoso —continuó el anciano con dulzura—. Quien busca un motivo para enfadarse siempre encontrará algo por lo que arder. Quien busca lo que está mal siempre encontrará una mancha oscura. Pero cuando te concentras solo en las manchas oscuras, quedas ciego al mar de bondad, de amor y de entrega que te rodea. Nadie intenta destruirte, Elrán. Eres tú quien envenena el agua de tu propio pozo, quien expulsa a los que te quieren y quien se deja helando en una oscuridad que él mismo ha creado\".",
  "Por primera vez en su vida, Elrán sintió que el muro de ira y de reproche empezaba a agrietarse. Apartó la mirada de la mancha negra y contempló la extensión blanca e infinita del lienzo.",
  "Cuando volvió a casa aquella noche, vio a su esposa sentada, exhausta, a sus hijos esperando con inquietud, y los muchos años de amor que lo habían esperado más allá de cada tormenta de rabia. Comprendió que la elección —ver la luz o perseguir las sombras— siempre había estado únicamente en sus manos.",
  "Cuando una persona elige fijarse solo en lo que falta, en los defectos y en las manchas oscuras, se convierte en la víctima eterna de una realidad que ella misma ha pintado de negro. Quien busca enemigos en cada rincón y aparta a quienes lo aman por cada ofensa imaginada acabará solo en el campo, no porque el mundo le diera la espalda, sino porque se negó a ver la bondad y el amor que le tendían.",
 ],
 "figs": [
  ("Elrán arrodillado en los jardines reales en flor, con el ceño fruncido ante una única hoja marchita en su mano, de espaldas a toda la belleza que lo rodea",
   "Elrán en los jardines reales: mil flores, y solo ve la hoja marchita."),
  ("Elrán furioso señalando una pequeña mancha desvaída en una alfombra de seda tejida con hilos de oro, mientras los sirvientes retroceden desconcertados",
   "Una alfombra de mil hilos de oro, y una mancha desvaída que la ensombreció entera."),
  ("La esposa de Elrán vaciando una cesta llena del mercado mientras los niños juegan, y Elrán en el umbral mirando con frialdad el único hueco vacío de la cesta",
   "Veinte especias en la cesta, y Elrán solo veía la que se había olvidado."),
  ("Una sábana enorme de seda blanca colgada en la plaza del pueblo con un diminuto punto de tinta en el centro, y Elrán ante ella gritando y señalando",
   "El Lienzo de la Verdad: una vasta extensión de seda pura y un punto de tinta del tamaño de un grano de sésamo."),
  ("El viejo tejedor abriendo la palma hacia la vasta seda blanca luminosa a su espalda, mientras Elrán permanece ante él atónito y en silencio",
   "\"¿Por qué elegiste ver solo el granito de tinta?\", y la ira se apagó."),
 ]},

3: {
 "title": "Las raíces de cedro de Arián",
 "topic": "la prueba de lealtad y la exigencia de romper todos los demás vínculos",
 "texts": [
  "En el reino de los Bosques Esmeralda, en un acantilado sobre el Río de Plata, vivían <strong>Arián</strong> y <strong>Mira</strong>. Mira era una mujer de corazón tormentoso y dolorido; llevaba dentro el recuerdo de un abandono antiguo y un miedo hondo a que nadie la amara de verdad. Arián, por su parte, la amaba con cada fibra de su alma y la había elegido como compañera por un compromiso profundo y sincero.",
  "Arián tenía raíces hondas en el reino. Su familia, sus hermanos y su clan vivían en el valle vecino. Eran gente sencilla y trabajadora, cálida y muy unida. Pero a ojos de Mira, cada lazo de Arián con su familia era una amenaza directa a su existencia. Veía un saludo de su hermano como un insulto disfrazado, y sus fiestas familiares como una maquinación destinada a alejar a Arián de ella.",
  "Cada vez que Arián bajaba al valle a saludar a sus hermanos o a celebrar con ellos, Mira estallaba en una tormenta de llanto y de rabia: \"¡No estás conmigo! Si de verdad me quisieras, ni siquiera respirarías el aire que ellos respiran. Ir a verlos es una traición hacia mí y hacia todo lo que he pasado. ¡Estás eligiendo a mis enemigos por encima de mi alma!\"",
  "Arián, que deseaba desesperadamente darle paz y demostrarle que ella era la única, empezó a renunciar. Primero dejó de acudir a las comidas de fiesta. Después evitaba la mirada de sus hermanos cuando se cruzaban en el sendero. Cada vez que cedía otro hilo de sus vínculos, esperaba que Mira se calmara y se sintiera por fin segura. Pero la llama que ardía en ella no se apagaba: solo exigía más y más pruebas.",
  "La boda en el valle",
  "Un día llegó un mensajero a su casa y anunció que el hermano menor de Arián iba a casarse, y que todo el clan esperaba que fuera a bendecirlo bajo el palio. Mira se plantó en el umbral, el rostro pálido y los ojos ardiendo: \"Si cruzas esta puerta y bajas a su boda, no tendrás adónde volver. Nos estarás condenando a la separación. ¡Eres un marido traidor que prefiere a su familia antes que a la mujer que renunció a su vida por él!\"",
  "Roto y aplastado, Arián se sentó en el umbral de la casa. Su corazón se partía entre el amor por Mira y la sangre que corría por sus venas.",
  "La guardabosques y el cedro",
  "Aquella noche apareció junto a la casa la vieja guardabosques, la guardiana de los pájaros. Vio a Arián encorvado y a Mira temblando de ira y de miedo dentro de la casa a oscuras. La anciana sacó de su zurrón una maceta pequeña con un cedro joven y hermoso.",
  "\"Mirad este árbol —les dijo a los dos—. Es fuerte, sus ramas son anchas y es capaz de dar sombra, amparo y refugio frente a las tormentas\".",
  "Entonces la anciana se volvió hacia Mira y dijo: \"Mira, le pides a Arián que sea tu escudo y solo tuyo. Pero para demostrar que te protege únicamente a ti, le exiges que corte todas sus raíces en la tierra, que seccione sus ramas familiares y que queme el bosque del que creció\".",
  "La anciana tomó unas tijeras y podó, una tras otra, todas las raíces del arbolito, hasta que no quedó más que un tronco desnudo y tembloroso. Lo puso en manos de Mira. En unos instantes las ramas se vencieron, las hojas amarillearon y el árbol se desplomó sin vida.",
  "\"El amor no es un boicot, y la entrega no es la exigencia de destruir el mundo de otra persona —le susurró la anciana a Mira, mientras a la mujer se le llenaban los ojos de lágrimas de espanto—. Un hombre al que le has cortado las raíces no podrá sostenerse en una tormenta ni protegerte. Se convertirá en una sombra hueca de sí mismo. Quien exige que su pareja demuestre el amor mediante el rechazo, el odio y la ruptura con su familia no busca una alianza: busca un compañero de celda en su propia soledad\".",
  "Mira miró el tronco muerto entre sus manos y luego alzó los ojos hacia Arián. Por primera vez no vio a un \"enemigo\" que se rebelaba contra ella, sino a un hombre que la amaba, consumido hasta la nada bajo el peso de sus pruebas imposibles.",
  "La verdadera seguridad y el verdadero amor no se construyen sobre las ruinas de otros vínculos, sino sobre la capacidad de dejar que aquel a quien amas florezca entero, con todas sus raíces y todas sus ramas.",
 ],
 "figs": [
  ("Arián y Mira en el bosque Esmeralda; Mira aferrada a su brazo con las dos manos, con un miedo hondo al abandono en los ojos",
   "Arián amaba a Mira con toda su alma, y Mira llevaba dentro el miedo a ser abandonada."),
  ("Un banquete familiar cálido en un valle soleado, con Arián al borde del encuadre, volviéndose a mirar con añoranza",
   "Su familia cálida en el valle vecino, y él al borde, mirando desde lejos."),
  ("Mira de pie, lanzando palabras con rabia y lágrimas, mientras Arián está sentado frente a ella con la cabeza gacha y los hombros hundidos",
   "\"Si vas a la boda, no tendrás adónde volver\"."),
  ("La guardabosques saliendo de la niebla a la luz de la luna, con una maceta y un cedro joven cuyas raíces sanas desbordan el borde",
   "La guardabosques apareció en la noche, trayendo un cedro joven."),
  ("El brote de cedro tendido en el suelo, desplomado y sin vida, con las raíces cortadas esparcidas a su lado y unas tijeras a sus pies",
   "Las raíces fueron podadas, y en unos instantes el árbol se desplomó."),
 ]},
}
