# -*- coding: utf-8 -*-
"""English translation, stories 4-7."""

EN_4_7 = {
4: {
 "title": "Razia's Waters of Revelation",
 "topic": "the illusion of mind-reading, and dressing others in malice",
 "texts": [
  "In the district of the Springs, beyond the mountains of Lebanon, lived <strong>Doron</strong>, a glassblower of gentle spirit, together with his partner <strong>Razia</strong>. Razia carried an old, burning wound: she believed the whole world ran on hidden schemes, and that no one was as innocent as they made themselves out to be.",
  "Inside Razia's mind a kind of translation machine ran without pause, turning every movement, glance or silence into deliberate malice. When Doron came home tired from a hard day's work and breathed deeply, Razia did not hear exhaustion – she \"heard\" a sigh of contempt. She flung at him at once: \"I know exactly what just went through your head! You sighed because you have had enough of me, you are only waiting for the moment you can run!\"",
  "When Doron's family spoke quietly in the next room about illness and making a living, Razia was utterly convinced they were whispering about her, turning him against her and hatching a plan to humiliate her. Even when Doron brought her a cup of hot tea on her weaker days, she saw it as \"lip service\", or an attempt to quiet a guilty conscience over injuries she claimed he was planning for the future.",
  "Doron would try again and again to explain, to swear to the purity of his intentions, to show his love – but Razia always cut his words off with the same scalding sentence: \"Don't play innocent! I read you like an open book. I know exactly what your real, ugly intentions are!\"",
  "The Waters of Revelation",
  "One day an old wandering magician came to their house, carrying an enchanted potion in a silver vial – <strong>the \"Waters of Revelation\"</strong>. Razia turned to the magician hopefully: \"Give my husband this potion to drink! I want all his dark and secret thoughts, all the schemes he weaves against me with his family and all the contempt he hides inside him to float to the surface, so that everyone can see who he really is!\"",
  "The magician smiled quietly and handed the vial to Doron. Doron drank the potion to the last drop without hesitating.",
  "Suddenly, Doron's thoughts and feelings began to take shape in the air of the room as living figures of colour and light. Razia stood tense, ready to see monsters of mockery and betrayal. But what appeared was something else entirely:",
  "She saw a figure of Doron walking down the street, thinking anxiously: \"What could I buy her to bring a smile to her tormented face?\" She saw him standing before his brothers, defending her fiercely and saying: \"Razia is sensitive and good, you have to understand how much she suffers, never be angry with her.\" She saw him lying in bed at night, his heart aching, praying in a quiet weeping: \"I wish she knew how much I love her, I wish she would stop seeing an enemy in me.\"",
  "There was not one single thought there of contempt, of mockery, or of scheming. There was only a sea of pain, of worry, and above all – a deep and faithful love worn down under the weight of suspicion.",
  "Razia froze. Her eyes widened in horror, not at what she saw in Doron, but at what she understood about herself.",
  "The magician looked at her and said gently: \"For years, Razia, you were not fighting the man who lives at your side. You were fighting monsters you created inside your own head. You turned your fears into prophecies, judged him for crimes he never committed, and dressed the purest heart ever held out to you in black intentions. Whoever listens only to his fears will always 'read' war in another's heart – even when the other is holding out peace.\"",
  "Razia looked at Doron, who stood before her with tearful eyes full of compassion. In that moment the poisonous translation machine in her mind fell silent.",
  "To save our world, we have to stop inventing another person's thoughts – and start believing the love that stands before us in reality.",
 ],
 "figs": [
  ("Doron the glassblower turning a globe of molten glass before the furnace, while Razia watches him suspiciously from the dark doorway",
   "Doron at the workshop – and Razia watching from the shadows."),
  ("Razia's thoughts twisting above her head into menacing shapes of smoke, while Doron, sitting opposite her, looks ordinary and warm",
   "The translation machine in her mind turned every gesture into deliberate malice."),
  ("A wandering magician in a patched coat holding out a crystal vial of glowing silver liquid that lights his fingers from within",
   "The \"Waters of Revelation\" – a potion that brings every inner thought to light."),
  ("Golden translucent figures of light rising in the air above the seated Doron, showing him defending Razia and praying in tears",
   "His thoughts rose into the air – and there was not a trace of malice in them."),
  ("Razia's face lit by the golden light of the thought-figures, her hand rising to her mouth and her eyes filling with tears",
   "Years of fighting monsters that were never there."),
 ]},

5: {
 "title": "Kai's Burden of Stones",
 "topic": "the trap of blame, turning a partner into the address for every frustration",
 "texts": [
  "High in the Crystal Mountains lived <strong>Kai</strong>, a diligent and big-hearted blacksmith, together with his partner <strong>Selin</strong>. Selin was a woman full of passion but haunted by fierce inner storms. Every time a cold gust of wind came into her house, every time the cooking pot boiled over, or every time a meeting with the townspeople ended in a feeling of unease – she would turn straight to Kai.",
  "But instead of sharing the burden, Selin made Kai the source of every misfortune: if she stumbled on a stone in the path, she flung at him: \"I fell because of you! You did not clear the way and you were not watching over me!\" If the sky darkened and rain soaked the cloths, she cried out: \"It is all because of you! You knew this would happen and you did not stop it, you always ruin everything for me!\" And if she felt distant from the rest of the village, she shouted in pain: \"It is your fault that I have no one! You did not fight hard enough for me, you are a useless husband!\"",
  "Kai, who loved her with all his heart and wanted only to shield her from her suffering, bowed his head and said nothing. He believed that his role as a partner was to be solid armour – to carry every accusation, to absorb every blow, and to hold all of her pain so that she would not fall apart.",
  "Every time she blamed him, Selin laid on Kai's back a heavy black basalt stone, saying: \"This is the weight of the pain you caused me.\" Kai carried the stones in silence, bending further and further, trying to keep smiling, to hand her a cup of water and to whisper: \"I am here, I will watch over you.\"",
  "The Tower on His Back",
  "Over the years the pile of stones on Kai's back became an enormous tower, too heavy to bear. His knees shook, his breath failed him, and his back broke slowly. He could no longer hold her, could no longer look into her eyes, and could not even walk at her side.",
  "One evening, when the soup scorched a little on the fire, Selin broke into a fresh storm: \"You see?! You have ruined everything again! You are to blame for everything wrong in my life!\" She took the heaviest stone she could find and hurled it with force onto the top of the pile on his back.",
  "In that moment there was an enormous cracking sound. Kai's knees collapsed and he fell to the floor, shackled and crushed beneath the weight of countless stones that had never been his. He lay motionless, utterly spent, his eyes gone out from the effort of surviving.",
  "Selin froze in horror. Around her the house stood empty, and the man who had always stood there, absorbing, soothing and protecting – lay helpless on the ground, unable to rise.",
  "The Mountain Healer",
  "Suddenly the old mountain healer appeared in the room. She looked at Kai lying beneath the rocks, and then looked at the weeping Selin: \"Why are you crying, Selin? You laid on him everything that hurt you.\"",
  "\"I wanted him to fix it all!\" Selin cried out in despair. \"I wanted him to be strong and to protect me from the whole world! Why did he break?!\"",
  "The old woman bent down and lifted one stone from the pile. \"Love is not a punching bag, and a partner is not a vessel for every frustration life brings,\" she said in a piercing voice. \"Instead of taking responsibility for the storms in your soul, you turned the one person who protected you into the target of your fury. You blamed him for every stone in your road, until you crushed the hands that wanted to hold you and the shoulders that wanted to carry you forward.\"",
  "Selin fell to her knees beside Kai, and with scratched hands began to clear the stones away, one after another.",
  "Whoever makes the one who loves him guilty of all his troubles will be left, in the end, alone – with the whole burden he refused to carry himself.",
 ],
 "figs": [
  ("Kai the blacksmith striking glowing iron in his forge high in the Crystal Mountains, with Selin standing beside him in the warm light",
   "Kai and Selin high in the Crystal Mountains."),
  ("Selin pointing at Kai in accusation and laying a heavy black basalt stone on his bowed back, while he takes it in silence",
   "Every accusation became another basalt stone on his back."),
  ("Kai climbing the stone path bent almost double beneath a tower of black basalt stones roped to his back, rising far above him",
   "The pile of stones grew into a tower too heavy to bear."),
  ("The tower of stones collapsed and scattered across the floor, Kai lying motionless among them while Selin stands over him frozen in horror",
   "His back broke with a crack – and the stones had never been his."),
  ("The old mountain healer kneeling beside the injured Kai, speaking to the weeping Selin who kneels opposite her among the black stones",
   "\"Love is not a punching bag\" – and only then did Selin understand."),
 ]},

6: {
 "title": "Noit's Cabin Foundations",
 "topic": "using separation and the threat of banishment as a weapon for control",
 "texts": [
  "On the slopes of the Crimson Mountains, in a warm cabin built of solid hewn stone, lived <strong>Dan</strong> and <strong>Noit</strong>. Dan had laboured for years to lay deep foundations, to build walls that would stand up to storms and to make their home a fortress of peace and love for their family.",
  "But Noit had a habit that cast a heavy shadow over the house: every time an argument broke out between them, every time she did not get exactly what she wanted, or every time she felt hurt and frustrated, she did not look for a way to talk. Instead, she drew the heaviest weapon of all. She would run to the front door, slam it hard and shout: \"Get out of the house! Never come back here! I am breaking it all, we are going to dissolve this, we will take this house apart today!\"",
  "Every time she flung those words at him, she would violently tear one stone out of the cabin's foundations and hurl it into the abyss. She believed that this would frighten him, force him to fold, and make him crawl on all fours to prove that he loved her.",
  "Dan would stand outside in the cold, his heart bleeding. He would try to make peace, to calm her, to promise it would be better – only so that she would not take apart the work of their lives. He would come back inside, hold her quietly, and try to put the stones back in their place.",
  "But the ritual repeated itself again and again. Dozens of times a year: an argument about a family visit – \"Get lost, we are filing for dissolution!\" (another stone torn from the wall). A disagreement over a word that was said – \"You are not a husband, you are an enemy, we are finished!\" (another roof beam broken).",
  "The Time He Walked Away",
  "One day a small argument broke out over something trivial. Noit, used to the power of the threat, screamed again: \"That is it! This time it is final! Get out of the house and you will never see me again!\"",
  "Dan looked at her in a long silence. His face was not angry, but empty and utterly tired. He did not plead, did not ask forgiveness and did not try to explain. He simply turned, stepped over the threshold, and walked slowly away down the path.",
  "Noit waited. She expected him to stand by the window, to knock at the door, to beg her to let him come back. But the hours went by, and the silence outside only deepened.",
  "Suddenly there was a deep and menacing creak. Noit looked up in horror: the ceiling had begun to sag, the walls were leaning to one side, and deep cracks were opening in the stones.",
  "Suddenly the mountain warden stood in the doorway. Noit cried out to her, weeping: \"The cabin is collapsing! Save me! Dan left and destroyed my home!\"",
  "The warden looked at the crumbling walls and said in a penetrating voice: \"Dan did not destroy this house, Noit. You did it with your own hands. A home is not an arena for games of power, and a marriage is not a rope you stretch to breaking point in every storm of feeling. Every time you drove him out, every time you threatened to smash it all and take everything apart, you pulled another stone from the foundations. You used the final threat as an everyday weapon – until there was nothing left to hold the roof over your head.\"",
  "Noit stood alone inside the ruins of the collapsed cabin.",
  "Whoever uses the threat of banishment and dissolution to win love will discover, in the end, that they have destroyed the only security on which love can stand.",
 ],
 "figs": [
  ("A solid stone cabin with a lit window on the slopes of the Crimson Mountains in golden sunset light",
   "The stone cabin on the slopes of the Crimson Mountains – a home built to stand."),
  ("Noit standing in the lit doorway, shouting and waving Dan out into the cold of the night",
   "\"Get out of the house! Never come back here!\""),
  ("Noit's hands wrenching a heavy stone out of the cabin's foundations, leaving a dark cavity as the stone falls into the abyss",
   "With every threat another stone was torn from the foundations."),
  ("Dan walking away down the mountain path with his back to the viewer, the lit cabin growing small behind him",
   "This time he did not plead and did not shout – he simply left."),
  ("The cabin collapsed into a heap of rubble on the mountainside, Noit standing before it alone beside the cloaked mountain warden",
   "\"Dan did not destroy this house – you did.\""),
 ]},

7: {
 "title": "Tamara's Bridges of Ash",
 "topic": "demanding perfection, refusing to forgive, and cutting every tie",
 "texts": [
  "In the kingdom of the Quiet Bay lived <strong>Eitan</strong>, a quiet and devoted ship's captain, together with his partner <strong>Tamara</strong>. Tamara was a woman of iron principles and a heart that knew no compromise. She had a rigid inner law: anyone who had ever said a word out of place, forgotten to invite her, looked at her in a way she could not read or hurt her feelings – was sentenced immediately to be an \"enemy for life\".",
  "The Black Book",
  "In the black book she kept in her head there were no pages of forgiveness: when her close neighbour did not stop to greet her because she was hurrying to tend to a sick child, Tamara declared: \"She is struck out. The wretch, I will never set foot on her doorstep again!\"",
  "When Eitan's family did not praise the pastry she brought to the festival meal enough, she forbade them to enter their home: \"They are wicked, they killed my soul, as far as I am concerned let them all die!\" And when Eitan tried to say that everyone is human and sometimes people make mistakes without meaning harm, she screamed: \"You are a traitor! Whoever does not hate my enemies – is my greatest enemy of all!\"",
  "The Bridge That Went Up in Flames",
  "Every time she cast out another person, Tamara would go out into their yard, take a burning torch, and set fire to another beam of the wide wooden bridge that connected their house to the rest of the village. Beam after beam, rope after rope – Tamara burned the ties with the neighbours, the bridge to the cousins, the path to the brothers, and the trail to the old friends.",
  "With every fire she felt a small victory of \"justice\": \"Now they will see. Now no one will be able to hurt me again.\" Eitan stood helpless before the flames, begging her to leave an opening, one small path for talking, but Tamara went on setting fire to every connecting thread.",
  "The Great Winter Day",
  "Until the great winter day came. A terrible storm, the like of which had never been seen, fell upon the bay. The waves threatened to drown the house, the winds tore at the roof, and the fire in the stove went out. The cold was bone-freezing, and the house began to give way.",
  "Tamara ran in alarm to the door of the house to call for help, but when she opened the door – her breath caught. Around their home a black, deep chasm had opened. All the bridges, every one – down to the last beam – were burned and charred.",
  "Across the chasm stood the villagers, the neighbours and the family, wrapped in warm coats, holding ropes and blankets. They wanted to reach out a hand, but there was no path by which they could come near.",
  "Tamara shouted into the wind in rage and tears: \"Look at them! They stand there and watch me freezing and do nothing! I knew they were all vile and wicked!\"",
  "Then Eitan laid his frozen hand on her shoulder and looked at her with pained, clear-eyed sorrow: \"Tamara, look down at the ashes. They did not leave you – you burned their way to you. Every time you demanded an impossible perfection, every time you struck a person out over a human mistake, you burned a bridge of kindness. Whoever declares war on the whole world and casts out everyone around them is not building themselves a fortress of protection – they are building themselves a lonely island of frost and death.\"",
  "The wind went on blowing over the burnt ash, and Tamara stood at the edge of the chasm.",
  "Whoever is not willing to hold any injury and to forgive any mistake sentences himself to drown in the storm – not because of the wickedness of others, but because of the fire he himself refused to put out.",
 ],
 "figs": []},
}
