# -*- coding: utf-8 -*-
"""Spanish translation, stories 4-7."""

ES_4_7 = {
4: {
 "title": "Las aguas de la revelación de Rasia",
 "topic": "la ilusión de leer la mente y vestir a los demás de malicia",
 "texts": [
  "En el distrito de los Manantiales, más allá de los montes del Líbano, vivía <strong>Dorón</strong>, un soplador de vidrio de espíritu apacible, junto a su compañera <strong>Rasia</strong>. Rasia arrastraba una herida antigua y ardiente: creía que el mundo entero se movía por tramas ocultas y que nadie era tan inocente como aparentaba.",
  "En la mente de Rasia funcionaba sin descanso una especie de máquina de traducir que convertía cada movimiento, cada mirada o cada silencio en malicia deliberada. Cuando Dorón volvía a casa cansado tras una dura jornada de trabajo y respiraba hondo, Rasia no oía agotamiento: \"oía\" un suspiro de desprecio. Le espetaba de inmediato: \"¡Sé exactamente lo que acaba de pasarte por la cabeza! Has suspirado porque estás harto de mí, ¡solo esperas el momento de poder huir!\"",
  "Cuando la familia de Dorón hablaba en voz baja en la habitación de al lado sobre enfermedades y sobre el sustento, Rasia estaba plenamente convencida de que cuchicheaban sobre ella, de que lo ponían en su contra y de que tramaban humillarla. Incluso cuando Dorón le llevaba una taza de té caliente en sus días más flojos, ella lo veía como \"un cumplido vacío\" o como un intento de acallar una mala conciencia por agravios que, según decía, él planeaba para el futuro.",
  "Dorón intentaba una y otra vez explicarse, jurar la pureza de sus intenciones, mostrarle su amor; pero Rasia le cortaba siempre las palabras con la misma frase abrasadora: \"¡No te hagas el inocente! Te leo como un libro abierto. ¡Sé exactamente cuáles son tus verdaderas y feas intenciones!\"",
  "Las aguas de la revelación",
  "Un día llegó a su casa un viejo mago errante con una poción encantada en un frasco de plata: <strong>las \"Aguas de la Revelación\"</strong>. Rasia se dirigió al mago llena de esperanza: \"¡Dale a beber esta poción a mi marido! Quiero que todos sus pensamientos oscuros y secretos, todas las tramas que teje contra mí con su familia y todo el desprecio que esconde dentro salgan a la superficie, ¡para que todos vean quién es en realidad!\"",
  "El mago sonrió en silencio y le tendió el frasco a Dorón. Dorón bebió la poción hasta la última gota sin vacilar.",
  "De pronto, los pensamientos y los sentimientos de Dorón empezaron a tomar forma en el aire de la sala como figuras vivas de color y de luz. Rasia estaba tensa, preparada para ver monstruos de burla y de traición. Pero lo que apareció fue algo muy distinto:",
  "Vio una figura de Dorón caminando por la calle y pensando con inquietud: \"¿Qué podría comprarle para arrancarle una sonrisa a su rostro atormentado?\" Lo vio de pie ante sus hermanos, defendiéndola con fiereza y diciendo: \"Rasia es sensible y buena, tenéis que entender cuánto sufre, no os enfadéis nunca con ella\". Lo vio tendido en la cama por la noche, con el corazón dolorido, rezando en un llanto callado: \"Ojalá supiera cuánto la quiero, ojalá dejara de ver en mí a un enemigo\".",
  "Allí no había un solo pensamiento de desprecio, ni de burla, ni de intriga. Solo había un mar de dolor, de preocupación y, sobre todo, un amor hondo y fiel desgastado bajo el peso de la sospecha.",
  "Rasia se quedó helada. Abrió mucho los ojos, horrorizada, no por lo que veía en Dorón, sino por lo que comprendía sobre sí misma.",
  "El mago la miró y dijo con dulzura: \"Durante años, Rasia, no luchabas contra el hombre que vive a tu lado. Luchabas contra monstruos que tú misma creabas dentro de tu cabeza. Convertiste tus miedos en profecías, lo juzgaste por crímenes que nunca cometió y vestiste de intenciones negras al corazón más limpio que te han tendido jamás. Quien solo escucha a sus miedos siempre 'leerá' guerra en el corazón del otro, aun cuando el otro le esté tendiendo la paz\".",
  "Rasia miró a Dorón, que estaba ante ella con los ojos llenos de lágrimas y de compasión. En ese instante, la máquina de traducir venenosa que había en su mente se calló.",
  "Para salvar nuestro mundo tenemos que dejar de inventar los pensamientos del otro y empezar a creer en el amor que tenemos delante, en la realidad.",
 ],
 "figs": [
  ("Dorón el soplador de vidrio girando un globo de vidrio fundido ante el horno, mientras Rasia lo observa con recelo desde el umbral en penumbra",
   "Dorón en el taller, y Rasia observando desde las sombras."),
  ("Los pensamientos de Rasia retorciéndose sobre su cabeza en formas amenazantes de humo, mientras Dorón, sentado frente a ella, parece corriente y cálido",
   "La máquina de traducir de su mente convertía cada gesto en malicia deliberada."),
  ("Un mago errante con un abrigo remendado tendiendo un frasco de cristal con un líquido plateado luminoso que le enciende los dedos por dentro",
   "Las \"Aguas de la Revelación\": una poción que saca a la luz cada pensamiento interior."),
  ("Figuras doradas y translúcidas de luz alzándose en el aire sobre Dorón sentado, mostrándolo defendiendo a Rasia y rezando entre lágrimas",
   "Sus pensamientos se alzaron en el aire, y no había en ellos rastro de malicia."),
  ("El rostro de Rasia iluminado por la luz dorada de las figuras de pensamiento, su mano subiendo hacia la boca y los ojos llenándose de lágrimas",
   "Años de luchar contra monstruos que nunca existieron."),
 ]},

5: {
 "title": "La carga de piedras de Kai",
 "topic": "la trampa de la culpa: convertir a la pareja en destinataria de toda frustración",
 "texts": [
  "En lo alto de las Montañas de Cristal vivía <strong>Kai</strong>, un herrero laborioso y de gran corazón, junto a su compañera <strong>Selín</strong>. Selín era una mujer llena de pasión pero acosada por tormentas interiores feroces. Cada vez que una ráfaga fría entraba en su casa, cada vez que la olla se desbordaba al hervir, o cada vez que un encuentro con la gente del pueblo terminaba en una sensación de incomodidad, se volvía directamente hacia Kai.",
  "Pero en lugar de compartir la carga, Selín hacía de Kai el origen de toda desgracia: si tropezaba con una piedra del camino, le espetaba: \"¡Me he caído por tu culpa! ¡No despejaste el camino y no me cuidabas!\" Si el cielo se oscurecía y la lluvia empapaba la ropa tendida, gritaba: \"¡Todo es culpa tuya! Sabías que iba a pasar y no lo impediste, ¡siempre me lo estropeas todo!\" Y si se sentía distante del resto del pueblo, gritaba con dolor: \"¡Es culpa tuya que no tenga a nadie! No luchaste bastante por mí, ¡eres un marido inútil!\"",
  "Kai, que la amaba con todo el corazón y solo quería resguardarla de su sufrimiento, agachaba la cabeza y callaba. Creía que su papel como compañero era ser una armadura firme: cargar con cada acusación, absorber cada golpe y sostener todo su dolor para que ella no se derrumbara.",
  "Cada vez que lo culpaba, Selín le colocaba a Kai en la espalda una pesada piedra de basalto negro, diciendo: \"Este es el peso del dolor que me has causado\". Kai cargaba las piedras en silencio, doblándose cada vez más, tratando de seguir sonriendo, de acercarle un vaso de agua y de susurrarle: \"Aquí estoy, yo te cuidaré\".",
  "La torre sobre su espalda",
  "Con los años, el montón de piedras sobre la espalda de Kai se convirtió en una torre enorme, demasiado pesada para sostenerla. Le temblaban las rodillas, le faltaba el aliento y la espalda se le rompía despacio. Ya no podía abrazarla, ya no podía mirarla a los ojos y ni siquiera podía caminar a su lado.",
  "Una tarde, cuando la sopa se quemó un poco en el fuego, Selín estalló en una nueva tormenta: \"¿Lo ves? ¡Lo has vuelto a arruinar todo! ¡Tienes la culpa de todo lo que va mal en mi vida!\" Cogió la piedra más pesada que encontró y la arrojó con fuerza sobre lo alto del montón que él llevaba a la espalda.",
  "En ese instante se oyó un crujido enorme. Las rodillas de Kai cedieron y cayó al suelo, encadenado y aplastado bajo el peso de incontables piedras que nunca habían sido suyas. Quedó inmóvil, agotado del todo, con los ojos apagados por el esfuerzo de sobrevivir.",
  "Selín se quedó helada de espanto. A su alrededor la casa estaba vacía, y el hombre que siempre había estado allí, absorbiendo, calmando y protegiendo, yacía indefenso en el suelo, incapaz de levantarse.",
  "La sanadora de la montaña",
  "De pronto apareció en la sala la vieja sanadora de la montaña. Miró a Kai tendido bajo las rocas y luego miró a Selín, que lloraba: \"¿Por qué lloras, Selín? Le pusiste encima todo lo que te dolía\".",
  "\"¡Yo quería que lo arreglara todo! —gritó Selín desesperada—. ¡Quería que fuera fuerte y me protegiera del mundo entero! ¿Por qué se ha roto?\"",
  "La anciana se agachó y levantó una piedra del montón. \"El amor no es un saco de boxeo, y una pareja no es un recipiente para cada frustración que trae la vida —dijo con voz penetrante—. En vez de hacerte responsable de las tormentas de tu alma, convertiste en blanco de tu furia a la única persona que te protegía. Lo culpaste por cada piedra de tu camino, hasta que aplastaste las manos que querían sostenerte y los hombros que querían llevarte adelante\".",
  "Selín cayó de rodillas junto a Kai y, con las manos arañadas, empezó a apartar las piedras, una tras otra.",
  "Quien hace culpable de todos sus males a quien lo ama acabará solo, con toda la carga que se negó a llevar él mismo.",
 ],
 "figs": [
  ("Kai el herrero golpeando el hierro incandescente en su fragua, en lo alto de las Montañas de Cristal, con Selín a su lado bajo la luz cálida",
   "Kai y Selín en lo alto de las Montañas de Cristal."),
  ("Selín señalando a Kai en actitud acusadora y colocando una pesada piedra de basalto negro sobre su espalda encorvada, mientras él la acepta en silencio",
   "Cada acusación se convertía en otra piedra de basalto sobre su espalda."),
  ("Kai subiendo el sendero de piedra doblado casi en dos bajo una torre de piedras de basalto negro atadas a su espalda, que se alza muy por encima de él",
   "El montón de piedras creció hasta ser una torre demasiado pesada para sostenerla."),
  ("La torre de piedras derrumbada y esparcida por el suelo, con Kai tendido inmóvil entre ellas mientras Selín lo contempla paralizada de espanto",
   "Su espalda se rompió con un crujido, y las piedras nunca habían sido suyas."),
  ("La vieja sanadora de la montaña arrodillada junto al herido Kai, hablando con Selín, que llora arrodillada frente a ella entre las piedras negras",
   "\"El amor no es un saco de boxeo\", y solo entonces lo entendió Selín."),
 ]},

6: {
 "title": "Los cimientos de la cabaña de Noit",
 "topic": "la separación y la amenaza de expulsión como arma de control",
 "texts": [
  "En las laderas de las Montañas Carmesí, en una cabaña cálida construida de piedra tallada y firme, vivían <strong>Dan</strong> y <strong>Noit</strong>. Dan había trabajado durante años para asentar cimientos hondos, levantar muros capaces de resistir las tormentas y hacer de su casa una fortaleza de paz y de amor para su familia.",
  "Pero Noit tenía una costumbre que arrojaba una sombra pesada sobre la casa: cada vez que estallaba una discusión entre ellos, cada vez que no conseguía exactamente lo que quería, o cada vez que se sentía herida y frustrada, no buscaba la manera de hablar. En lugar de eso, echaba mano del arma más pesada de todas. Corría a la puerta de entrada, la abría de golpe y gritaba: \"¡Fuera de esta casa! ¡No vuelvas nunca! Lo rompo todo, nos separamos, ¡hoy mismo desmontamos esta casa!\"",
  "Cada vez que le lanzaba esas palabras, arrancaba con violencia una piedra de los cimientos de la cabaña y la arrojaba al abismo. Creía que aquello lo asustaría, lo obligaría a ceder y lo haría arrastrarse a cuatro patas para demostrarle que la quería.",
  "Dan se quedaba fuera, en el frío, con el corazón sangrando. Intentaba hacer las paces, calmarla, prometerle que todo mejoraría, solo para que ella no desmontara la obra de sus vidas. Volvía a entrar, la abrazaba en silencio y trataba de devolver las piedras a su sitio.",
  "Pero el ritual se repetía una y otra vez. Decenas de veces al año: una discusión por una visita familiar, \"¡Lárgate, presentamos la separación!\" (otra piedra arrancada del muro). Un desacuerdo por una palabra dicha, \"No eres un marido, eres un enemigo, ¡hemos terminado!\" (otra viga del tejado partida).",
  "El día que se marchó",
  "Un día estalló una pequeña discusión por una nimiedad. Noit, acostumbrada al poder de la amenaza, gritó de nuevo: \"¡Se acabó! ¡Esta vez es definitivo! ¡Fuera de esta casa y no volverás a verme nunca!\"",
  "Dan la miró en un silencio largo. Su rostro no era de ira, sino de vacío y de un cansancio total. No suplicó, no pidió perdón y no intentó explicarse. Simplemente se dio la vuelta, cruzó el umbral y se alejó despacio sendero abajo.",
  "Noit esperó. Esperaba que se quedara junto a la ventana, que llamara a la puerta, que le rogara que lo dejara volver. Pero pasaban las horas, y el silencio de fuera solo se hacía más hondo.",
  "De pronto se oyó un crujido hondo y amenazante. Noit alzó la vista horrorizada: el techo había empezado a ceder, los muros se inclinaban hacia un lado y en las piedras se abrían grietas profundas.",
  "De repente, la guardiana de la montaña se plantó en el umbral. Noit le gritó, llorando: \"¡La cabaña se derrumba! ¡Sálvame! ¡Dan se ha ido y ha destruido mi casa!\"",
  "La guardiana miró los muros que se desmoronaban y dijo con voz penetrante: \"Dan no ha destruido esta casa, Noit. Lo has hecho tú con tus propias manos. Un hogar no es un ruedo para juegos de poder, y un matrimonio no es una cuerda que se tensa hasta romperla en cada tormenta de sentimientos. Cada vez que lo echabas, cada vez que amenazabas con romperlo todo y desmontarlo todo, arrancabas otra piedra de los cimientos. Usaste la amenaza última como arma cotidiana, hasta que no quedó nada que sostuviera el techo sobre tu cabeza\".",
  "Noit se quedó sola dentro de las ruinas de la cabaña derrumbada.",
  "Quien usa la amenaza de la expulsión y de la ruptura para ganarse el amor descubrirá, al final, que ha destruido la única seguridad sobre la que el amor puede sostenerse.",
 ],
 "figs": [
  ("Una cabaña sólida de piedra con una ventana iluminada en las laderas de las Montañas Carmesí, bajo la luz dorada del atardecer",
   "La cabaña de piedra en las laderas de las Montañas Carmesí: un hogar construido para durar."),
  ("Noit de pie en el umbral iluminado, gritando y echando a Dan al frío de la noche",
   "\"¡Fuera de esta casa! ¡No vuelvas nunca!\""),
  ("Las manos de Noit arrancando una piedra pesada de los cimientos de la cabaña, dejando un hueco oscuro mientras la piedra cae al abismo",
   "Con cada amenaza se arrancaba otra piedra de los cimientos."),
  ("Dan alejándose por el sendero de la montaña, de espaldas al espectador, con la cabaña iluminada empequeñeciéndose tras él",
   "Esta vez no suplicó ni gritó: simplemente se marchó."),
  ("La cabaña derrumbada en un montón de escombros en la ladera, con Noit ante ella, sola, junto a la guardiana de la montaña embozada",
   "\"Dan no destruyó esta casa: la destruiste tú\"."),
 ]},

7: {
 "title": "Los puentes de ceniza de Tamara",
 "topic": "exigir perfección, negarse a perdonar y cortar todos los vínculos",
 "texts": [
  "En el reino de la Bahía Tranquila vivía <strong>Eitán</strong>, un capitán de barco callado y entregado, junto a su compañera <strong>Tamara</strong>. Tamara era una mujer de principios de hierro y de un corazón que no conocía el término medio. Tenía una ley interior rígida: cualquiera que alguna vez hubiera dicho una palabra fuera de lugar, hubiera olvidado invitarla, la hubiera mirado de un modo que ella no supiera descifrar o le hubiera herido los sentimientos, quedaba condenado de inmediato a ser \"enemigo de por vida\".",
  "El libro negro",
  "En el libro negro que guardaba en la cabeza no había páginas de perdón: cuando su vecina cercana no se detuvo a saludarla porque iba con prisa a atender a un hijo enfermo, Tamara sentenció: \"Queda tachada. ¡La miserable, no volveré a pisar su umbral jamás!\"",
  "Cuando la familia de Eitán no elogió bastante el pastel que ella llevó a la comida de fiesta, les prohibió entrar en su casa: \"Son perversos, mataron mi alma, ¡por mí que se mueran todos!\" Y cuando Eitán intentaba decirle que todos somos humanos y que a veces la gente se equivoca sin mala intención, ella gritaba: \"¡Eres un traidor! ¡Quien no odia a mis enemigos es mi peor enemigo!\"",
  "El puente que ardió en llamas",
  "Cada vez que expulsaba a otra persona, Tamara salía al patio, tomaba una antorcha encendida y prendía fuego a otra viga del ancho puente de madera que unía su casa con el resto del pueblo. Viga tras viga, cuerda tras cuerda, Tamara quemó los lazos con los vecinos, el puente hacia los primos, el camino hacia los hermanos y la senda hacia los viejos amigos.",
  "Con cada incendio sentía una pequeña victoria de \"justicia\": \"Ahora verán. Ahora ya nadie podrá volver a herirme\". Eitán se quedaba impotente ante las llamas, rogándole que dejara una abertura, un pequeño camino para hablar, pero Tamara seguía prendiendo fuego a cada hilo que unía.",
  "El gran día de invierno",
  "Hasta que llegó el gran día de invierno. Una tormenta terrible, como nunca se había visto, se abatió sobre la bahía. Las olas amenazaban con anegar la casa, los vientos arrancaban el tejado y el fuego de la estufa se apagó. El frío calaba los huesos, y la casa empezó a ceder.",
  "Tamara corrió alarmada a la puerta de la casa para pedir ayuda, pero cuando la abrió se quedó sin aliento. Alrededor de su hogar se había abierto un abismo negro y profundo. Todos los puentes, todos y cada uno, hasta la última viga, estaban quemados y carbonizados.",
  "Al otro lado del abismo estaban los aldeanos, los vecinos y la familia, envueltos en abrigos gruesos, con cuerdas y mantas en las manos. Querían tenderle una mano, pero no había camino alguno por el que acercarse.",
  "Tamara gritó al viento con rabia y con lágrimas: \"¡Miradlos! ¡Están ahí mirando cómo me congelo y no hacen nada! ¡Sabía que todos eran viles y perversos!\"",
  "Entonces Eitán le puso la mano helada sobre el hombro y la miró con una tristeza dolorida y lúcida: \"Tamara, mira hacia abajo, mira la ceniza. Ellos no te abandonaron: tú quemaste el camino que llevaba hasta ti. Cada vez que exigiste una perfección imposible, cada vez que tachaste a una persona por un error humano, quemaste un puente de bondad. Quien le declara la guerra al mundo entero y expulsa a todos los que lo rodean no se construye una fortaleza de protección: se construye una isla solitaria de hielo y de muerte\".",
  "El viento seguía soplando sobre la ceniza quemada, y Tamara estaba de pie al borde del abismo.",
  "Quien no está dispuesto a sostener ninguna ofensa ni a perdonar ningún error se condena a ahogarse en la tormenta, no por la maldad de los demás, sino por el fuego que él mismo se negó a apagar.",
 ],
 "figs": []},
}
