# -*- coding: utf-8 -*-
"""English translation, stories 1-3. `texts` follows the order of the p/h/moral
blocks in the Hebrew source; `figs` follows the order of its illustrations."""

EN_1_3 = {
1: {
 "title": "Liryon's Armour of Mirrors",
 "topic": "hypersensitivity, low self-worth and the sense of being persecuted",
 "texts": [
  "In the kingdom of the Emerald Valley, deep in a forest of ancient oaks, there lived a small, gentle creature with soft fur, named <strong>Liryon</strong>. Liryon had a heart made of thin crystal – he felt every breath of wind with the force of a storm, and every falling leaf sounded to him like rolling thunder.",
  "But a heavy shadow followed Liryon: he believed with all his heart that he was small, flawed, and unworthy of love. And because he thought that of himself, he was certain that every other creature in the forest saw him exactly the same way – and that all of them, without a single exception, were plotting to hurt him or to mock him.",
  "The Shield That Became a Wall",
  "To protect his fragile heart, Liryon built himself a garment like no other: armour made of shards of clouded mirror. He believed the armour would dazzle anyone who looked at him and would guard him against the world's arrows of ridicule.",
  "But the mirrors of that armour were warped: when the forest fox looked his way and smiled kindly, Liryon saw in the mirrors a smile of scorn and contempt. When a flock of birds chirped excitedly on a nearby branch, Liryon heard malicious whispers plotting to cast him out. When the hedgehog offered to share a juicy fruit, Liryon was sure it was an attempt to poison him, or to prove to him that he was too weak to find food himself.",
  "Every time someone came close, Liryon would snarl, cry out at the injustice being done to him, and declare a boycott: \"I will never speak to any of you again! You are all cruel, you are all against me, and I alone am left to suffer in this world!\"",
  "He cast out the fox, shunned the birds, and slammed his door in the hedgehog's face.",
  "Alone in a Tower of Glass",
  "As time went on, the creatures of the forest – who loved Liryon and wanted him near – tried again and again to leave flowers, letters of peace and small gifts on his doorstep. But in every gesture Liryon saw a fresh insult:",
  "\"They send flowers to remind me how pitiful I am,\" he muttered bitterly to himself. \"They are only trying to quiet their guilty consciences.\"",
  "In the end, the creatures of the forest grew weary. The pain of having every kind intention read as deliberate cruelty became too heavy a burden. They began to keep their distance, stepping quietly around his house so as not to rouse his anger.",
  "Liryon sat inside his darkened house, wrapped in the heavy armour of mirrors, and looked out of the window. When he saw the forest empty around him, hot tears ran down his cheeks:",
  "\"I knew it,\" he whispered in searing pain. \"I knew they all hated me. Look how they cast me out and left me alone in the world. Everyone is against me, and I am the poor victim of them all.\"",
  "The Old Owl and the Clear Spring",
  "One day, an old and wise owl with eyes as deep as the night landed on Liryon's windowsill. Liryon knitted his brows at once and shouted: \"Have you come as well, to look down on me and to wound me?!\"",
  "The owl did not retreat and did not take offence. He only said, quietly: \"Dear Liryon, the armour you wear is so very heavy. Come with me to the spring of truth at the mountain's summit. If the spring shows that they truly do all hate you, I will stay here and protect you forever.\"",
  "Liryon, who wanted to prove to the owl how right he was and how everyone was to blame for his state, followed him.",
  "When they reached the summit, Liryon stood over the clearest waters in the kingdom. He looked into them to see his own pitiful, outcast figure, but saw only the clouded mirror shards of his armour, throwing back at him countless reflections of his own face – furious, frightened and full of suffering.",
  "\"Take off the armour for one moment, Liryon,\" said the owl gently. \"Look into the water without your mirrors.\"",
  "With trembling hands, Liryon loosened the straps and let the heavy armour of mirrors fall away. He bent over the water. Instead of monsters or enemies, he saw a gentle creature with beautiful eyes, wounded deep inside. And when he looked around him without the warped mirrors, he suddenly saw the forest path as it was: he saw the hedgehog who had left a basket of fresh strawberries by his door out of concern; he saw the birds who had sung a song of longing; and he understood that the fox had only been trying to smile at him with affection.",
  "\"No one hated you, Liryon,\" the owl whispered. \"The only enemy that ever hunted you was the thought that you were not worthy of love. Because you did not believe in your own worth, you turned every hand held out to you into a fist, and every smile into mockery. You are the one who cast out a world that only wanted to hold you.\"",
  "The Healing of the Heart",
  "In that moment something broke inside Liryon – not a breaking of pain, but a deep release. He left the armour of mirrors on the mountain top and went down into the valley in his bare, vulnerable fur.",
  "When he reached the valley, he demanded no protection and blamed no one. He simply opened his door, looked at his neighbours and said: \"I was wrong. My pain made me see enemies in you, when you were the family that only ever wanted what was good for me.\"",
  "And in the Emerald forest, no one held his past against him. They simply took him back, because all along – every step of the way – they had only been waiting for him to agree to be healed of his own fear.",
  "When a person is held captive by low self-worth and hypersensitivity, he turns himself into the centre of a hostile world that does not exist. Whoever reads every movement as an injury and every person as an enemy sentences himself to isolation and bitterness – and convinces himself that he is the world's victim, when in truth he is the prisoner of his own fears.",
 ],
 "figs": [
  ("Liryon, a small white creature with a glowing crystal heart, sitting alone in an ancient forest holding a shard of mirror",
   "Liryon and his heart of thin crystal – every breath of wind sounded to him like a storm."),
  ("Liryon in heavy armour made of clouded mirror shards, his red heart glowing through the cracks",
   "The armour meant to protect him – shards of clouded mirror that filtered everything he saw."),
  ("A hedgehog offering Liryon a ripe fig, while the reflection in the mirror armour shows the hedgehog snarling and threatening",
   "The hedgehog held out ripe fruit – but in the warped mirrors it looked like a snarl."),
  ("Liryon in his armour sitting hunched and alone at the foot of a tree, a basket of fruit left beside him by the forest creatures watching from afar",
   "The gifts stayed where they were left, and the forest watched from a distance – loneliness inside armour."),
  ("Liryon without his armour, glowing in warm light, touching the water of the spring of truth while the mirror shards lie on the shore and the forest animals look on",
   "At the spring of truth, without the armour, he saw himself for the first time – and who had been waiting on the shore."),
  ("Liryon standing at sunset by the lake surrounded by a hedgehog, a rabbit, a badger, a squirrel and a fawn, the mirror shards lying behind him",
   "At sunset, with the shards left behind, Liryon found he had never been alone."),
 ]},

2: {
 "title": "Elran's Cloth of Truth",
 "topic": "a compulsive focus on what is missing and on flaws",
 "texts": [
  "In the heart of the kingdom of Dawnlight, where the sun always stroked the rooftops with golden light and the fields yielded sweet fruit, lived the royal keeper of the gardens, <strong>Elran</strong>. Elran had a sharp eye and a rare sensitivity to every small nuance, but he also had one trait that darkened his whole world: he never managed to see the light in full, because his eyes were always drawn, compulsively, to the dark spots.",
  "If a beautiful silk carpet was woven for him with a thousand golden threads and only one tiny faded spot, Elran would stand over the carpet, point furiously at that single spot, and cry out: \"Look at this ugliness! This carpet is completely ruined, and whoever wove it did so deliberately, to hurt me!\"",
  "The Missing Spice",
  "Inside his home, his devoted and loving wife had built a whole world with him. She laboured, she cooked, she raised their children and saw to his every need. But Elran did not see the decades of devotion, the warm meals or the honest care. If she came back from the market having forgotten one spice out of twenty, he did not see the full basket – he saw only the spice that was missing.",
  "He would fling at her that she held him in contempt, that he had never mattered to her, and that all through the years she had only been looking for ways to diminish him and break his spirit.",
  "When his family and neighbours invited him to their celebrations, Elran would scan the room like a hunter looking for prey. If someone did not greet him with a wide enough smile, if someone spoke with another person and did not turn to him at once, or if his brother travelled to a family occasion without telling him beforehand – Elran would fill with an inner burning.",
  "He would turn every innocent gesture into a malicious plot, shun his relatives, declare that they were \"enemies who destroyed his soul\", and demand that everyone around him boycott them too, as proof of absolute loyalty to his pain.",
  "As the years passed, Elran became a lonely, bitter and exhausted man. His home became a fortress where every word was weighed in fear of setting off a new storm of accusations. He was convinced that he was the most wronged and most injured man in the whole kingdom, that the entire world was weaving plots against him, and that no one understood the depth of his suffering.",
  "The Cloth of Truth",
  "One day, an old and wise weaver came to the city carrying a cloth like no other – <strong>the \"Cloth of Truth\"</strong>. The cloth was white, soft and magnificent, and at its centre was a small black dot of ink, the size of a sesame seed. The weaver set the cloth up in the town square and invited the people to look at it.",
  "Elran stood before the cloth, his gaze locking at once onto the black stain, his face reddening with anger: \"What a disgrace! How dare you display in the town square a cloth so stained, so ugly and so flawed? You are mocking us all!\"",
  "The old weaver looked at Elran with quiet, compassionate eyes, and asked him calmly: \"Elran, look closely. Here is an enormous sheet of pure white silk, a thousand threads of light, months of work meant to bring warmth and beauty. Why, out of all this white and magnificent expanse, did you choose to see only the little grain of ink, and to judge the whole cloth by it?\"",
  "Elran froze where he stood, lost for words.",
  "\"You look for the flaw because inside yourself you feel flawed,\" the old man went on gently. \"Whoever looks for a reason to be angry will always find one to burn over. Whoever looks for what is wrong will always find a dark spot. But when you focus only on the dark spots, you are blind to the sea of goodness, love and devotion surrounding you. No one is trying to destroy you, Elran. You are the one poisoning the water of your own well, casting out those who love you, and leaving yourself freezing in a darkness of your own making.\"",
  "For the first time in his life, Elran felt the wall of anger and blame begin to crack. He moved his gaze away from the black stain and looked at the endless white expanse of the cloth.",
  "When he returned home that evening, he saw his wife sitting exhausted, his children waiting anxiously, and the many years of love that had waited for him beyond every storm of rage. He understood that the choice – to see the light or to chase the shadows – had always rested in his hands alone.",
  "When a person chooses to focus only on what is missing, on the flaws and on the dark spots, he makes himself the eternal victim of a reality he has painted black himself. Whoever looks for enemies in every corner and drives away those who love him over every imagined slight will find himself, in the end, alone on the field – not because the world turned its back on him, but because he refused to see the goodness and the love that were held out to him.",
 ],
 "figs": [
  ("Elran kneeling in the blooming royal gardens, scowling at a single withered leaf in his hand, his back to all the beauty around him",
   "Elran in the royal gardens – a thousand flowers, and all he sees is the withered leaf."),
  ("Elran raging and pointing at a small faded patch on a silk carpet woven with golden threads, while the servants draw back bewildered",
   "A carpet of a thousand golden threads – and one faded spot that darkened all of it."),
  ("Elran's wife unpacking a full market basket while their children play, as Elran stands in the doorway staring coldly at the one empty space in the basket",
   "Twenty spices in the basket, and Elran saw only the one that was forgotten."),
  ("An enormous white silk sheet hanging in the town square with a tiny dot of ink at its centre, Elran standing before it shouting and pointing",
   "The Cloth of Truth: a vast expanse of pure silk, and one dot of ink the size of a sesame seed."),
  ("The old weaver opening his palm towards the vast glowing white silk behind him, while Elran stands before him stunned and silent",
   "\"Why did you choose to see only the grain of ink?\" – and the anger fell quiet."),
 ]},

3: {
 "title": "Arian's Cedar Roots",
 "topic": "the loyalty test and the demand to tear other bonds apart",
 "texts": [
  "In the kingdom of the Emerald Forests, on a cliff overlooking the Silver River, lived <strong>Arian</strong> and <strong>Mira</strong>. Mira was a woman with a stormy, aching heart; she carried within her the memory of an old abandonment, and a deep fear that no one truly loved her. Arian, for his part, loved her with every fibre of his soul and had chosen her as his partner out of a deep and genuine commitment.",
  "Arian had deep roots in the kingdom. His family, his brothers and his clan lived in the neighbouring valley. They were simple working people, warm and close-knit. But in Mira's eyes, every tie Arian had with his family was a direct threat to her existence. She saw a greeting from his brother as a disguised insult, and their family celebrations as a scheme designed to draw Arian away from her.",
  "Every time Arian went down to the valley to greet his brothers or to celebrate with them, Mira would break into a storm of weeping and rage: \"You are not with me! If you really loved me, you would not even breathe the air they breathe. Going to them is a betrayal of me and of everything I have been through. You are choosing my enemies over my soul!\"",
  "Arian, who desperately wanted to give her peace and to prove to her that she was the one and only, began to give things up. First he stopped coming to the festival meals. Then he avoided meeting his brothers' eyes when they passed on the path. Every time he gave up another thread of his ties, he hoped Mira would calm and would finally feel safe. But the flame inside her did not go out – it only demanded more and more proof.",
  "The Wedding in the Valley",
  "One day a messenger came to their house and announced that Arian's younger brother was to be married, and that the whole clan expected him to come and give his blessing beneath the canopy. Mira stood in the doorway, her face pale and her eyes burning: \"If you cross this threshold and go down to their wedding, you will have nowhere to come back to. You will be sentencing us to separation. You are a treacherous husband who prefers his family over the woman who gave up her life for you!\"",
  "Broken and crushed, Arian sat on the doorstep of the house. His heart was torn between his love for Mira and the blood running in his veins.",
  "The Forest Warden and the Cedar",
  "That night the old forest warden, the keeper of the birds, appeared beside the house. She saw Arian bowed over and Mira trembling with rage and fear inside the darkened house. The old woman drew from her pack a small pot holding a young and beautiful cedar tree.",
  "\"Look at this tree,\" she said to them both. \"It is strong, its branches are wide, and it is able to give shade, protection and shelter from storms.\"",
  "Then the old woman turned to Mira and said: \"Mira, you are asking Arian to be your shield and yours alone. But to prove that he protects only you, you are demanding that he cut away all his roots in the earth, sever his family branches and burn down the forest he grew from.\"",
  "The old woman took a pair of shears and pruned away, one after another, every root of the little tree, until nothing was left but a bare, trembling trunk. She placed it in Mira's hands. Within moments the branches drooped, the leaves yellowed and the tree collapsed, lifeless.",
  "\"Love is not a boycott, and devotion is not a demand to destroy another person's world,\" the old woman whispered to Mira, as tears of shock filled the woman's eyes. \"A man whose roots you have cut away will not be able to stand in a storm and protect you. He will become a hollow shadow of himself. Whoever demands that a partner prove love through shunning, hatred and a rift with his family is not looking for a covenant – he is looking for a fellow prisoner in his own loneliness.\"",
  "Mira looked at the dead trunk in her hands, and then raised her eyes to Arian. For the first time she saw not an \"enemy\" rebelling against her, but a loving man worn to nothing under the weight of her impossible tests.",
  "Real security and real love are not built on the ruins of other bonds, but on the ability to let the one you love flourish whole – with all his roots and all his branches.",
 ],
 "figs": [
  ("Arian and Mira in the Emerald forest; Mira clutching his arm with both hands, a deep fear of abandonment in her eyes",
   "Arian loved Mira with all his soul – and Mira carried within her the fear of being left."),
  ("A warm family feast in a sunlit valley, with Arian standing at the edge of the frame, turning to look back with longing",
   "His warm family in the neighbouring valley – and he at the edge, watching from afar."),
  ("Mira standing and hurling words in rage and tears, while Arian sits facing her with his head bowed and his shoulders sunken",
   "\"If you go to the wedding, you will have nowhere to come back to.\""),
  ("The forest warden stepping out of the mist in the moonlight, carrying a pot with a young cedar whose healthy roots spill over the rim",
   "The forest warden appeared in the night, carrying a young cedar."),
  ("The cedar sapling lying collapsed and lifeless on the ground, its severed roots scattered beside it and a pair of shears at its foot",
   "The roots were pruned away – and within moments the tree collapsed."),
 ]},
}
